### ISSUE TITLE
ToDo Aug 06 - Aug 07

### ISSUE THREAD

**Issue by DanielDomingueti** [DanielDomingueti/crypto-trade-bot#1]
## First steps
 - [x] Define on paper two different versions including a simulation and a real trading system.
 - [x] Define business rules
    - [x] database tables
    - [x] endpoints and routes
    - [x] trading scenarios
    - [x] data flow
 - [x] Check Binance API's docs to learn how it works
 - [x] Define indicators DBB, EMA, MACD, RSI, SMA. (next release)
 - [x] Start writing README
 - [x] keep tb_investment steady and update tb_bank_statement when buying or selling
 - [x] refactor General Info on Notion
