### ISSUE TITLE
ToDo | Aug 27 - 31

### ISSUE THREAD

**Issue by DanielDomingueti** [DanielDomingueti/crypto-trade-bot#3]
## Database population
- [x] Define initial database migration (populate static databases).
- [x] Create repositories.
- [x] Explain what each route does. 
- [x] Start admin implementation
