### ISSUE TITLE
ToDo | October

### ISSUE THREAD

**Issue by DanielDomingueti** [DanielDomingueti/crypto-trade-bot#5]
## October 1st up to 31th.
 - [x] Fix security layer
 - [ ] CRUD implementations for left modules.
 - [ ] Create populate sql files
 - [ ] Define RSI indicators for trading simulations

 ## LATER
 - [ ] Search for documentation models
